<<<<<<< HEAD
name: app2
=======
name: app1
>>>>>>> c83ffe5d00f6fb7b89f2adfa194c039aa44cbe87
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
<<<<<<< HEAD
=======
  http: ^1.6.0
>>>>>>> c83ffe5d00f6fb7b89f2adfa194c039aa44cbe87
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
